# DIME Analytics Resource Directory {#resources}

The resources listed in this appendix are mentioned elsewhere in the chapters of this book,
and this appendix includes them all in one place for easy reference.
All these resources are made public under generous open-source licenses.
This means that you are free to use, reuse, and adapt these resources for any purpose as you see fit,
so long as you include an appropriate citation.

## Public resources and tools {-}

**DIME Wiki.** One-stop shop for impact evaluation research solutions. The DIME Wiki is a resource focused on practical implementation guidelines rather than theory, open to the public, easily searchable, suitable for users of varying levels of expertise, up-to-date with the latest technological advances in electronic data collection, and curated by a vibrant network of editors with expertise in the field.
Hosted at https://dimewiki.worldbank.org.

**Stata Visual Library.** A curated, easy-to-browse selection of graphs created in Stata. Clicking on each graph reveals the source code, to allow for easy replication. 
Hosted at https://worldbank.github.io/stata-visual-library/.

**R Econ Visual Library.** A curated, easy-to-browse selection of graphs created in R. Clicking on each graph reveals the source code, to allow for easy replication.
Hosted at https://worldbank.github.io/r-econ-visual-library/.

**DIME Analytics Research Standards.** A repository outlining DIME’s public commitments to research ethics, transparency, reproducibility, data security and data publication, along with supporting tools and resources.
Hosted at https://github.com/worldbank/dime-standards.

## Flagship training courses {-}

**Manage Successful Impact Evaluations (MSIE).**
  DIME Analytics’ flagship training is a week-long annual course,
held in person in Washington, DC. MSIE is intended to improve the skills and knowledge of impact evaluation (IE) practitioners,
familiarizing them with critical issues in IE implementation,
recurring challenges, and cutting-edge technologies.
The course consists of lectures and hands-on sessions.
Through small group discussions and interactive computer lab sessions,
participants work together to apply what they’ve learned and have a first-hand opportunity to develop skills.
Hands-on sessions are offered in parallel tracks,
with different options based on software preferences and skill level.
The course materials are available at https://osf.io/h4d8y/.

**Manage Successful Impact Evaluation Surveys (MSIES).**
  A fully virtual course, in which participants learn the workflow for primary data collection.
The course covers best practices at all stages of the survey workflow,
from planning to piloting instruments and monitoring data quality once fieldwork begins.
There is a strong focus throughout on research ethics and reproducible workflows.
The course uses a combination of virtual lectures,
case studies, readings, and hands-on exercises.
The course materials are available at https://osf.io/resya/.

**Research Assistant Onboarding Course.**
  This course is designed to familiarize Research Assistants and Research Analysts with DIME’s standards for data work.
By the end of the course’s six sessions,
participants have the tools and knowledge to implement best practices for transparent and reproducible research.
The course focuses on how to set up a collaborative workflow for code,
datasets, and research outputs.
Most content is platform-independent and software-agnostic,
but participants are expected to be familiar with statistical software.
The course materials are available at https://osf.io/qtmdp.

**Introduction to R for Advanced Stata Users.** 
This course is an introduction to the R programming language, 
building upon knowledge of Stata. The course focuses on common tasks in development research, 
related to descriptive analysis, data visualization, data processing, and geospatial data work. 
Materials available at https://osf.io/nj6bf.

**DIME Analytics Trainings.** 
DIME Analytics’ home on the Open Science Framework, 
with links to materials for all past courses and technical trainings.
Visit https://osf.io/wzjtk to explore the materials.

## Software tools and trainings {-}

**ietoolkit.** Suite of Stata commands to routinize common tasks for data management and impact evaluation analysis.
Developed at https://github.com/worldbank/ietoolkit.

**iefieldkit.** Suite of Stata commands to routinize and document common tasks in primary data collection.
Developed at https://github.com/worldbank/iefieldkit.

**DIME Analytics GitHub Trainings and Resources.** A GitHub repository containing all the GitHub training materials and
resources developed by DIME Analytics.
The trainings follow DIME’s model for organizing research teams on GitHub,
and are designed for face-to-face delivery,
but materials are shared so that they may be used and adapted by others.
Hosted at https://github.com/worldbank/dime-github-trainings.

**DIME Analytics LaTeX Training.** A user-friendly guide to getting started with LaTeX.
Exercises provide opportunities to practice creating appendices,
exporting tables from R or Stata to LaTeX,
and formatting tables in LaTeX.
Available at https://github.com/worldbank/DIME-LaTeX-Templates.
