# Abbreviations {-}

**3ie** - International Initiative for Impact Evaluation

**AEA** – American Economic Association

**API** – application programming interface

**ATE** – average treatment effect

**AWS** – Amazon Web Services

**CAPI** – computer-assisted personal interviewing

**CSL** – Citation Styles Library

**DIME** – Development Impact Evaluation

**DOI** – Digital object identifier

**EGAP** – Evidence in Governance and Politics

**EPS** – encapsulated PostScript

**FDE** - full disk encryption

**FSE** - file system encryption

**GPS** – global positioning system

**HFC** – High-Frequency Checks

**IAT** – implicit association test

**ID** – identifier or identification

**IPA** – Innovations for Poverty Action

**IRB** – Institutional Review Board

**IV** – Instrumental Variables

**J-PAL** – Abdul Latif Jameel Poverty Action Lab

**MDE** – Minimum Detectable Effect

**MSIE** – Manage Successful Impact Evaluations

**MSIES** – Manage Successful Impact Evaluation Surveys

**ODK** – Open Data Kit

**OLS** – Ordinary Least Squares

**OSF** – Open Science Framework

**PAP** – preanalysis plan

**PDF** – portable document format

**PII** – Personally-Identifying Information

**PNG** – portable network graphic

**RCT** – Randomized Control Trial

**RD** – Regression Discontinuity

**RIDIE** – Registry for International Development Impact Evaluations

**SSC** – Statistical Software Components

**URL** - Uniform Resource Locator

**USB** – universal serial bus

**VPN** - Virtual Private Network
