# Acknowledgements {-}

::: {.summary}
<br>This book is dedicated to all the Development Impact Evaluation (DIME) team members
who have wrangled data without being taught how,
hustled to get projects done on time,
wondered if they really should get their PhD after all,
and in doing so made this knowledge necessary and possible.
:::

We thank all the people who helped us get here, especially Arianna Legovini,
for her leadership at DIME, unending support of our work, and detailed comments on this book,
and Florence Kondylis, for her leadership in founding and growing DIME Analytics
and supporting this project from the very first.
We also thank the following members of DIME Analytics for
their contributions to the ideas in this book and their help organizing them:
Roshni Khincha,
Avnish Singh,
Patricia Paskov,
Radhika Kaul,
Mizuhiro Suzuki,
Yifan Powers, and
Maria Arnal Canudo.
This work has been financially supported by the United Kingdom
Foreign, Commonwealth & Development Office (FCDO) through
the DIME i2i Umbrella Facility for Impact Evaluation at the World Bank.

Our gratitude to the many people who read and offered feedback as the book took shape:
<!-- Alphabetical by last name -->
Stephanie Annijas,
Maria Camila Ayala Guerrero,
Kaustubh Chahande,
Thomas Escande,
Aram Gassama,
Steven Glover,
Nausheen Khan,
Robert Norling,
Michael Orevba,
Caio Piza,
Francesco Raffaelli,
Daniel Rogger,
Ankriti Singh,
Ravi Somani, and
Leonardo Viotti.
Although they number far too many to name individually,
we also thank all the members of DIME and
its teams over the years for the innovative work they have done,
the lessons learned, and
the team spirit that makes our work so fruitful and rewarding.

This published version of the book has been revised repeatedly
since its internal release in June 2019,
with extensive feedback from readers and experts.
We additionally thank Vincenzo di Maro (manager, DIME3)
for his support throughout this process,
as well as peer reviewers
David McKenzie (lead economist, World Bank),
Holly Krambeck (program manager, World Bank),
Alaka Holla (program manager, World Bank),
Jim Shen (senior manager, Abdul Latif Jameel Poverty Action Lab),
Federica di Battista (trialling lead, FCDO), and
Gabriel Vicente, Rajee Kanagavel, and Maksim Pecherskiy
from the Development Data Partnership team.

This book is a living product that is written and maintained publicly.
For the code and edit history,
see https://github.com/worldbank/dime-data-handbook;
for online and PDF copies,
visit https://worldbank.github.io/dime-data-handbook/.
The website includes updated instructions
for providing feedback as well as notes on updates to the content.
Whether you work with DIME, the World Bank,
or another organization or university,
we ask that you read the contents of this book critically.
We welcome feedback and corrections to improve the book.
Please visit https://worldbank.github.io/dime-data-handbook/feedback to provide feedback.
You can also email us at dimeanalytics@worldbank.org,
and we will be very thankful.
We hope that you enjoy *Development Research in Practice*!
