# Feedback {-}

This book is a living resource. It was developed and is updated through GitHub at https://github.com/worldbank/dime-data-handbook.
We encourage feedback and corrections so that we can improve the contents of the book in future editions. We hope that this book will be the platform for a creative and constructive discussion on this topic from which new best practices will emerge. Please feel free to provide any type of feedback, no matter how small, as these work together to improve the content overall. Anything from missing content, content that was poorly or insufficiently explained to content you think is incorrect. 

> We are particularly excited to collaborate with the wider Stata community on the Stata style guide.

## How to contribute {-}

You can always send us an email with any type of feedback to dimeanalytics@worldbank.org. If you are familiar with GitHub, you can create [issues](https://github.com/worldbank/dime-data-handbook/issues) with suggestions or open a pull request.


## Already addressed errata {-}

In this section we will publish all error reports received that we have already addressed in the digital, and will be included in the next printed edition. 
