# DIME Analytics Resource Directory {#resources}

The resources listed in this appendix are mentioned throughout this book. This
appendix provides them in one place for easy reference. All of these resources
are made public under generous open-source licenses. This means that they are
free to use, reuse, and adapt for any purpose, so long as they are cited
appropriately.

## Public resources and tools {-}

*DIME Wiki*. One-stop shop for impact evaluation research solutions. The DIME
Wiki is a resource focused on practical implementation guidelines rather than
theory, open to the public, easily searchable, suitable for users of varying
levels of expertise, up-to-date with the latest technological advances in
electronic data collection, and curated by a vibrant network of editors with
expertise in the field. Hosted at <https://dimewiki.worldbank.org>.

*Stata Visual Library*. A curated, easy-to-browse selection of graphs created in
Stata. Clicking on each graph reveals the source code, allowing for easy
replication. Hosted at <https://worldbank.github.io/stata-visual-library>.


*R Econ Visual Library*. A curated, easy-to-browse selection of graphs created
in R. Clicking on each graph reveals the source code, allowing for easy
replication. Hosted at <https://worldbank.github.io/r-econ-visual-library>.

*DIME Analytics Research Standards*. A repository outlining DIME’s public
commitments to research ethics, transparency, reproducibility, data security,
and data publication, along with supporting tools and resources. Hosted at
<https://github.com/worldbank/dime-standards>.


## Flagship training courses {-}


*Manage Successful Impact Evaluations (MSIE)*. The flagship training of DIME
Analytics. MSIE is a week-long annual course, held in person in Washington, DC.
MSIE is intended to improve the skills and knowledge of impact evaluation
practitioners, familiarizing them with critical issues in impact evaluation
implementation, recurring challenges, and cutting- edge technologies. The course
consists of lectures and hands-on sessions. Through small group discussions and
interactive computer lab sessions, participants work together to apply what they
have learned and have an opportunity to develop their skills. Hands-on sessions
are offered in parallel tracks, with different options based on software
preferences and skill level. Course materials available at
<https://osf.io/h4d8y>.

*Manage Successful Impact Evaluation Surveys (MSIES)*. A fully virtual course in
which participants learn the workflow for primary data collec- tion. The course
covers best practices at all stages of the survey workflow, from planning to
piloting instruments and monitoring data quality once fieldwork begins. There is
a strong focus throughout on research ethics and reproducible workflows. The
course uses a combination of virtual lectures, case studies, readings, and
hands-on exercises. Course materials available at <https://osf.io/resya>.

*Research Assistant Onboarding Course*. A course designed to familiarize
research assistants and research analysts with DIME’s standards for data work.
By the end of the course’s six sessions, participants have the tools and
knowledge to implement best practices for transparent and reproducible research.
The course focuses on how to set up a collabora- tive workflow for code, data
sets, and research outputs. Most content is platform-independent and
software-agnostic, but participants are expected to be familiar with statistical
software. The course materials are available at <https://osf.io/qtmdp>.

*Introduction to R for Advanced Stata Users*. An introduction to the R
programming language, building on knowledge of Stata. The course focuses on
common tasks in development research related to descriptive analysis, data
visualization, data processing, and geospatial data work. Materials available at
<https://osf.io/nj6bf>.

*DIME Analytics Trainings*. The DIME Analytics homepage on the Open Science
Framework includes links to materials for all past courses and technical
trainings. Materials available at <https://osf.io/wzjtk>.


## Software tools and trainings {-}

`ietoolkit`. A suite of Stata commands to routinize common tasks for data
management and impact evaluation analysis. Developed at
<https://github.com/worldbank/ietoolkit>.

`iefieldkit`. A suite of Stata commands to routinize and document common tasks
in primary data collection. Developed at
<https://github.com/worldbank/iefieldkit>.

*DIME Analytics GitHub Trainings and Resources*. A GitHub repository containing
all the GitHub training materials and resources developed by DIME Analytics. The
trainings follow DIME’s model for organizing research teams on GitHub and are
designed for face-to-face delivery, but materials are shared so that they may be
used and adapted by others. Hosted at
<https://github.com/worldbank/dime-github-trainings>.

*DIME Analytics LaTeX Training*. A user-friendly guide to getting started with
LaTeX. Exercises provide opportunities to practice creating appen- dixes,
exporting tables from R or Stata to LaTeX, and formatting tables in LaTeX.
Available at <https://github.com/worldbank/DIME-LaTeX-Templates>.
